### ISSUE TITLE
May I ask when will release the checkpoints？ 

### ISSUE THREAD

**Issue by hangzeli** [EmilianPostolache/stable-audio-controlnet#1]

**Comment by EmilianPostolache** [comment]
Dear hangzeli, I will upload them today. I will also write an inference jupyter notebook for easy inference but it will take more time. Thank you!

**Comment by EmilianPostolache** [comment]
Checkpoints for audio conditioned model trained on MusDB have been shared.

**Comment by jamesWalker55** [comment]
Apologies for commenting on a closed issue, might you consider releasing the `chroma` and `envelope` models as well?

**Comment by EmilianPostolache** [comment]
Hy, the `chroma` model is postponed indefinitely. The envelope model will be released here https://github.com/ispamm/Stable-V2A as part of the code for our paper https://arxiv.org/abs/2412.15023 (works great!)

**Comment by jamesWalker55** [comment]
Thanks for the prompt reply! I'll have a look at your paper!
